package org.l1ving.api.issue

data class Issue(
        var active_lock_reason: Any? = null,
        var assignee: User? = null,
        var assignees: List<User>? = null,
        var author_association: String? = null,
        var body: String? = null,
        var closed_at: Any? = null,
        var closed_by: Any? = null,
        var comments: Int? = null,
        var comments_url: String? = null,
        var created_at: String? = null,
        var events_url: String? = null,
        var html_url: String? = null,
        var id: Long? = null,
        var labels: List<Label>? = null,
        var labels_url: String? = null,
        var locked: Boolean? = null,
        var milestone: Milestone? = null,
        var node_id: String? = null,
        var number: Int? = null,
        var performed_via_github_app: Any? = null,
        var repository_url: String? = null,
        var state: String? = null,
        var title: String? = null,
        var updated_at: String? = null,
        var url: String? = null,
        var user: User? = null
)