package org.l1ving.api.issue

data class Issue(
        val active_lock_reason: Any? = null,
        val assignee: User? = null,
        val assignees: List<User>? = null,
        val author_association: String? = null,
        val body: String? = null,
        val closed_at: Any? = null,
        val closed_by: Any? = null,
        val comments: Int? = null,
        val comments_url: String? = null,
        val created_at: String? = null,
        val events_url: String? = null,
        val html_url: String? = null,
        val id: Long? = null,
        val labels: List<Label>? = null,
        val labels_url: String? = null,
        val locked: Boolean? = null,
        val milestone: Milestone? = null,
        val node_id: String? = null,
        val number: Int? = null,
        val performed_via_github_app: Any? = null,
        val repository_url: String? = null,
        val state: String? = null,
        val title: String? = null,
        val updated_at: String? = null,
        val url: String? = null,
        val user: User? = null
)