package org.l1ving.api.issue

data class Issue(
    var active_lock_reason: Any?,
    var assignee: User?,
    var assignees: List<User>?,
    var author_association: String?,
    var body: String?,
    var closed_at: Any?,
    var closed_by: Any?,
    var comments: Int?,
    var comments_url: String?,
    var created_at: String?,
    var events_url: String?,
    var html_url: String?,
    var id: Long?,
    var labels: List<Label>?,
    var labels_url: String?,
    var locked: Boolean?,
    var milestone: Milestone?,
    var node_id: String?,
    var number: Int?,
    var performed_via_github_app: Any?,
    var repository_url: String?,
    var state: String?,
    var title: String?,
    var updated_at: String?,
    var url: String?,
    var user: User?
)